-- Municipios
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 1, 'Amaxac De Guerrero') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 2, 'Apetatitlan De Antonio Carvajal') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 3, 'Apizaco') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 4, 'Atlangatepec') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 5, 'Atltzayanca') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 6, 'Calpulalpan') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 7, 'El Carmen Tequexquitla') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 8, 'Cuapiaxtla') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 9, 'Cuaxomulco') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 10, 'Chiautempan') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 11, 'Muñoz De Domingo Arenas') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 12, 'Españita') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 13, 'Huamantla') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 14, 'Hueyotlipan') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 15, 'Ixtacuixtla De Mariano Matamoros') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 16, 'Ixtenco') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 17, 'Mazatecochco De Jose Maria Morelos') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 18, 'Contla De Juan Cuamatzi') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 19, 'Tepetitla De Lardizabal') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 20, 'Sanctorum De Lazaro Cardenas') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 21, 'Nanacamilpa De Mariano Arista') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 22, 'Acuamanala De Miguel Hidalgo') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 23, 'Nativitas') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 24, 'Panotla') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 25, 'San Pablo Del Monte') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 26, 'Santa Cruz Tlaxcala') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 27, 'Tenancingo') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 28, 'Teolocholco') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 29, 'Tepeyanco') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 30, 'Terrenate') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 31, 'Tetla De La Solidaridad') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 32, 'Tetlatlahuca') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 33, 'Tlaxcala') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 34, 'Tlaxco') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 35, 'Tocatlan') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 36, 'Totolac') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 37, 'Zitlaltepec De Trinidad Sanchez Santos') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 38, 'Tzompantepec') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 39, 'Xaloztoc') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 40, 'Xaltocan') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 41, 'Papalotla De Xicohtencatl') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 42, 'Xicohtzinco') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 43, 'Yauhquemehcan') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 44, 'Zacatelco') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 45, 'Santa Apolonia Teacalco') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 46, 'Santa Cruz Quilehtla') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 47, 'San Juan Huactzinco') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 48, 'Santa Catarina Ayometla') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 49, 'Santa Isabel Xiloxoxtla') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 50, 'San Jose Teacalco') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 51, 'San Francisco Tetlanohcan') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 52, 'La Magdalena Tlaltelulco') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 53, 'San Damian Texoloc') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 54, 'Emiliano Zapata') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 55, 'Lazaro Cardenas') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 56, 'San Jeronimo Zacualpan') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 57, 'San Lucas Tecopilco') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 58, 'Santa Ana Nopalucan') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 59, 'San Lorenzo Axocomanitla') ON CONFLICT DO NOTHING;
INSERT INTO municipios (estado_id, clave_ine, nombre) VALUES (29, 60, 'Benito Juarez') ON CONFLICT DO NOTHING;
